<?php

use App\Models\User;
use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $user_Email=[
            "work.abdulhaseeb@gmail.com",
            "majidabdulshakoor@gmail.com",
            "abdullahjibransohrani7@gmail.com"	,
            "abdullah.salman23@gmail.com",
            "ar20252025@gmail.com",
            "abdurrehman101202@gmail.com",
            "affan.haider@gmail.com	",
            "needahmed2@gmail.com",
            "iahsan958@gmail.com",
            "alisaeed.345@gmail.com",
            "ibnebilal27@gmail.com"	,
            "maribsiddiqui95@gmail.com"	,
            "arslanatahir@gmail.com"	,
            "ashir.sheikh98@gmail.com",
            "Bassam.10hasan@gmail.com",
            "bilalafzal237@gmail.com"	,
            "muneebmansoor123@gmail.com",
            "danishali0051@gmail.com",
            "fahadawan631@gmail.com",
            "qazisaifurrehman777@gmail.com",
            "bilalhamza0987@gmail.com",
            "hamzahaider333@gmail.com",
            "hassan.nazir99@gmail.com",
            "hasnainiftikhar100@gmail.com",
            "ibrahimaamer10@gmail.com"	,
            "aarishrai7@gmail.com"	,
            "M.ahmadqureshi10@gmail.com",
            "alishahid619619@gmail.com"	,
            "ehti0987@gmail.com"	,
            "hashirmalik2222@gmail.com"	,
            "abbaskhurram479@gmail.com"	,
            "mahadshahid91@gmail.com"	,
            "mirsabnadeem123@gmail.com"	,
            "msmanzoor91@gmail.com"	,
            "msharjeelnaeem@gmail.com"	,
            "mohammadtalhairfan@gmail.com",
            "umairchd786@gmail.com"	,
            "alnoorprinters@ymail.com"	,
            "moeez.arshad2597@gmail.com"	,
            "muhaaiminnawaz1999@gmail.com"	,
            "muneeb.ahd1@gmail.com"	,
            "murshidsaif1999@gmail.com"	,
            "murtazabutt31610@gmail.com"	,
            "mutoyib.bsir655@iiu.edu.pk"  ,
            "rajaabdullah796@gmail.com"	,
            "ishahzaib632@gmail.com",
            "syedazazulhassan@yahoo.com",
            "ch238682@gmail.com"	,
            "usmanbashircheema@gmail.com"	,
            "adenarchitects@gmail.com"	,
            "zaigham.tauqeer91@gmail.com"	,

           " shirazyasin@hotmail.com	",
                "maz3tt@hotmail.com",
               " omartanveer@outlook.com",
               ' rajaabdullah796@gmail.com'	,
                'osama.shahid184@gmail.com	',
               ' daud.minhas@gmail.com	',
               ' Tanzeel745@gmail.com	',
              '  pxhamza20@gmail.com	',
                'malijamali94@gmail.com	',
               ' osambabar1@gmail.com'	,
               ' CA.danishakbar@gmail.com	',
               ' Influencerfashion953@gmail.com	',
               ' faizan.shaheen14@gmail.com	',
                'ibrahim_naeem@outlook.com'	,
               ' hassebtariq23@gmail.com	',
               ' shehrozehaiderhanif@gmail.com'	,
               ' jatgjatg129@gmail.com	',
              '  zainulabideen4744@gmail.com	',
               ' armantariq1313@gmail.com	',
               'hirra.zafar23@gmail.com',
                'farhanaabbasi15@gmail.com	',
               'adilmaham9@gmail.com'	,
                'malaikanadeem172@gmail.com	',
               ' arishahaq22@gmail.com'	,
                'sadaf.cheema@kcl.ac.uk'	,
               ' manal_aziz@windowslive.com',
                'faisalkidwai@yahoo.com	',
                'noureenrazzaq07@gmail.com',
                'fakhrunisa28@yahoo.com	',
                'rubabhania@gmail.com'	,
               'meeshkhan@yahoo.com	',
                'khalidmaham43@gmail.com',
               ' dr.riz198@gmail.com'	,
               ' ishahamad1131@gmail.com',
                'amna.ghaffar999@gmail.com'	,
                'ellahiruhsana@yahoo.com',
                'sobia786zahid@gmail.com	',
                'sadiaadeel505@gmail.com'	,
                'abeera.faiqsiddiqui@gmail.com	',
                'ayeshainayat319@gmail.com'	,
                'adorableainu@gmail.com'	,
                'samra.sana@yahoo.com'	,
                'asma.masoodhussain@live.com'	,
                'fmobeen95@gmail.com'	,
                'ffayfareed80@gmail.com'	,
                'ayeshatariqq007@gmail.com'	,
                'sobiashahrukh@gmail.com'	,


        ];

        $fullname=[
            'Abdul Haseeb Khan	',
            'Abdul Majid',
            'Abdullah jibran',
            'Abdullah Saleem',
            'Abdulrehman'	,
            'Abdurrehman khan',
            'Affan Haider'	,
            'Ahmed Pervez'	,
            'Ahsan Iqbal	',
            'Ali Saeed'	,
            'Anas bilal'	,
            'Anas Siddiqui'	,
           ' Arsalan tahir'	,
            'Ashir Farooq'	,
            'Bassam Hasan'	,
            'Bilal Afzal'	,
            'Chaudhry M Muneeb Mansoor'	,
           'Danish Ali'	,
            'Fahad Hussain'	,
            'HAFIZ SAIF UR REHMAN'	,
            'Hamza Bilal',
            'Hamza Haider'	,
            'Hasan bin Nazir'	,
            'Hasnain Iftikhar',
           'Ibrahim Aamer'	,
            'M Aarish Rai'	,
           ' M Ahmad Qureshi'	,
            'M Ali Shahid'	,
            'M Ehtisham Chaudhary',
            'M Hashir Waheed'	,
            'M Khurram Abbass'	,
            'M Mahad Shahid	',
            'M Mirsab Nadeem',
           'M Shahbaz Manzoor',
            'M Sharjeel Naeem',
            'M Talha Irfan'	,
            'M Umair Rasheed',
            'M Umer Bashir Cheema'	,
            'Moeez Arshad'	,
            'Muhaaimin Nawaz Khan',
            'Muneeb Ahmad'	,
            'Murshid Saif'	,
           'Murtaza Butt'	,
            'Mutoyib Malik'	,
            'Raja Abdullah'	,
            'Shahzaib Minhas'	,
            'Syed Azaz Ul Hassan',
            'Umar Aziz'	,
            'Usman Cheema',
            'waqqas naeem'	,
            'Zaigham Tauqeer'	,
            'Shiraz Yasin'	,
            'mazhar kaunain',
            'Omar Tanveer'	,
            'Raja Abdullah'	,
           'Osama Shahid Ahmed	',
           'Daud Mustafa Minhas',
            'Tanzeel Ur Rehman'	,
           'Abdullah Bin Kamran',
            'Muhammad Ali'	,
            'OsamA Babar',
            'Danish Akbar'	,
            'Hafizhashim'	,
            'Faizan Shaheen'	,
            'Ibrahim Naeem' 	,
            'Muhammad Haseeb Tariq'	,
            'Shehroze Haider Hanif' ,
            'Jamil Ahmad'	,
            'Zain Ul Abideen'	,
            'Arman Tariq'	,
            'Adv Hirra Zafar'	,
            'Farhana Abbasi' ,
            'Maham Adil' 	,
            'Malaika Nadeem',
            'Arisha'	,
            'Sadaf Cheema ',
            'Manal Aziz'	,
            'Inayah Kidwai',
            'Noureen' 	,
            'Fakhru-Nisa' ,
           ' Hania Rubab'	,
            'Ayesha Hammad'	,
            'Maham Khalid' 	,
            'Rizwana Imran'	,
            'Isha Khan'	,
            'Amna Ghaffar' 	,
            'Ruhsana Ellahi',
           ' Sobia Zahid'	,
            'Sadia Adeel'	,
           ' Abeera Tariq'	,
            'Ayesha Inayat'	,
           ' Unaiza Mustafa' ,
           ' Samra Sana'	,
           ' Asma masood hussain',
            'Fatima Mobeen',
            'Fatima Fareed ',
          '  Ayesha Tariq'	,
           ' Sobia abid'	,


        ];
        User::create(
            [
                'login_id'  => 'admin',
                'user_type' => 'Admin',
                'full_name' => 'Admin',
                'password'  => bcrypt('admin'),
                'phone'     => '01234567891',
                'email'     => 'admin@' . config('app.name') . ".com",
            ]
        );
        User::create(
            [
                'login_id'  => 'teacher',
                'user_type' => 'Teacher',
                'full_name' => 'Teacher',
                'password'  => bcrypt('teacher'),
                'phone'     => '01234567891',
                'email'     => 'teacher@' . config('app.name') . ".com",
            ]
        );


        User::create(
            [
                'login_id'  => 'student',
                'user_type' => 'Student',
                'full_name' => 'Student',
                'password'  => bcrypt('student'),
                'phone'     => '01234567891',
                'email'     => 'student@' . config('app.name') . ".com",
            ]
        );

        $count = 0;

        foreach( $user_Email as $user){
            User::create(
                [
                    'login_id'  => $user,
                    'user_type' => 'Student',
                    'full_name' => $fullname[$count],
                    'password'  => bcrypt('Allahisone'),
                    'phone'     => '01234567891',
                    'email'     => $user,
                ]
            );
            $count++;

        }
    }
}
